{
  "id":79,
  "name":"formbuilder_fields",
  "formtabs":[
    {
      "MIGX_id":1,
      "caption":"Field",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":2,
          "field":"type",
          "caption":"Field Type",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"listbox",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"radio==radio||checkbox==checkbox||text==text||textarea==textarea||information==information||hidden==hidden",
          "default":"text"
        },
        {
          "MIGX_id":6,
          "field":"name",
          "caption":"Field Name",
          "description":"Select one or use a extended field",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"listbox",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"Extended Field||email||firstname||lastname||phone||address||zip||city||message",
          "default":""
        },
        {
          "MIGX_id":1,
          "field":"extendedname",
          "caption":"Extended Name",
          "description":"this is required for Extended Fields!",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":4,
          "field":"label",
          "caption":"Label",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":5,
          "field":"description",
          "caption":"Description",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"textarea",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":7,
          "field":"class",
          "caption":"CSS class",
          "description":"css class for this field",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    },
    {
      "MIGX_id":3,
      "caption":"Validation",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":6,
          "field":"validate",
          "caption":"Validate",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"checkbox",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"required||blank||email||allowTags||isNumber||isDate",
          "default":""
        },
        {
          "MIGX_id":7,
          "field":"custom_validate",
          "caption":"Custom Validate",
          "description":"Alternatively to the checkboxes, you can put all formit-validation-rules for that field here, see http:\/\/rtfm.modx.com\/display\/ADDON\/FormIt.Validators",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    },
    {
      "MIGX_id":2,
      "caption":"Options",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":3,
          "field":"inputoptions",
          "caption":"Input Options",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"migx",
          "configs":"formbuilder_fields_inputoptions:migxformbuilder",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    },
    {
      "MIGX_id":4,
      "caption":"Value",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":1,
          "field":"getvaluefromrequest",
          "caption":"Get Value from Request",
          "description":"Get the value from request. The fieldname has to be the same as the request-param.",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"checkbox",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"yes==1",
          "default":""
        }
      ]
    },
    {
      "MIGX_id":5,
      "caption":"Custom Chunks",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":1,
          "field":"buildform_chunk",
          "caption":"Form",
          "description":"chunkname for Formfield",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":2,
          "field":"buildmailreport_chunk",
          "caption":"Mail",
          "description":"chunkname for Mailreport - field",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":3,
          "field":"viewformrequest_chunk",
          "caption":"View",
          "description":"chunkname for CMP - view - field",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":4,
          "field":"buildautorespondreport_chunk",
          "caption":"Autorespond",
          "description":"chunkname for autorespondmail - field",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    }
  ],
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"[]",
  "extended":{
    "migx_add":"Create Field",
    "formcaption":"Field",
    "update_win_title":"Formbuilder Field",
    "win_id":"formbuilder_fields",
    "maxRecords":"",
    "multiple_formtabs":"",
    "extrahandlers":"",
    "packageName":"migxformbuilder",
    "classname":"",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "getlistwhere":"",
    "joins":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"Name",
      "dataIndex":"name",
      "width":20,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    },
    {
      "MIGX_id":3,
      "header":"Label",
      "dataIndex":"label",
      "width":30,
      "renderer":"",
      "sortable":"false",
      "show_in_grid":1
    },
    {
      "MIGX_id":2,
      "header":"Type",
      "dataIndex":"type",
      "width":30,
      "renderer":"",
      "sortable":"false",
      "show_in_grid":1
    },
    {
      "MIGX_id":4,
      "header":"Extended Name",
      "dataIndex":"extendedname",
      "width":30,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    }
  ],
  "createdby":2,
  "createdon":"2012-09-16 22:43:33",
  "editedby":1,
  "editedon":"2013-05-16 13:04:41",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2013-04-29 01:00:00",
  "publishedby":0
}