{
  "id":83,
  "name":"formbuilder_fields_inputoptions",
  "formtabs":[
    {
      "MIGX_id":1,
      "caption":"Input Option",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":2,
          "field":"value",
          "caption":"Value",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":1,
          "field":"label",
          "caption":"Label",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    }
  ],
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"[]",
  "extended":{
    "migx_add":"",
    "formcaption":"",
    "update_win_title":"migxformbuilder Input options",
    "win_id":"formbuilder_fields_inputoptions",
    "multiple_formtabs":"",
    "extrahandlers":"",
    "packageName":"migxformbuilder",
    "classname":"",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "getlistwhere":"",
    "joins":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"Label",
      "dataIndex":"label",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    },
    {
      "MIGX_id":2,
      "header":"Value",
      "dataIndex":"value",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":"[]"
    }
  ],
  "createdby":1,
  "createdon":"2013-05-03 11:54:08",
  "editedby":1,
  "editedon":"2013-05-03 12:47:51",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2013-05-03 01:00:00",
  "publishedby":0
}